### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ruslanraupoff** [kkcodes/laravel-firebase-auth#2]
Uncaught TypeError: Cannot read property 'providerId' of null
    at signInSuccess (login:119)
    at Fk (firebaseui.js:291)
    at Ek (firebaseui.js:289)
    at firebaseui.js:323

**Comment by kkcodes** [comment]
Can you please provide more details? The sign in method used. And, Have you filled the .env file with the required details?

**Comment by ruslanraupoff** [comment]
https://github.com/kkcodes/laravel-firebase-auth/blob/master/resources/views/auth_login.blade.php#L63
returned null
![image](https://user-images.githubusercontent.com/16702915/40888810-39bdfdc0-6776-11e8-89b2-44cfcb93ded0.png)

**Comment by kkcodes** [comment]
Can you please share the sign in provider you are using ? I have tried for both Google and Facebook and it is working completely fine.
