### ISSUE TITLE
redirect url

### ISSUE THREAD

**Issue by ihsansaleemkhan** [kkcodes/laravel-firebase-auth#3]
signInSuccessUrl: '<url-to-redirect-to-on-success>',

I want to redirect to my home page, 

The data's are not inserting into our local server into firebase_users table

**Comment by kkcodes** [comment]
Hi,

Are you getting any errors in the console? If yes, then do share that.

For the redirection, it redirects to the page that you have in your LoginController for the key `$redirectTo`.

**Comment by ihsansaleemkhan** [comment]
tnx for the reply, 

Yes i am getting errors in console
![capture](https://user-images.githubusercontent.com/33631614/41739425-a388d244-75b2-11e8-8aff-cdb838974b0b.PNG)

**Comment by kkcodes** [comment]
Hi, 

Can you please try the same in incognito mode and let me know if you are getting the same result. Because the error is generated from Firebase's end.
