### ISSUE TITLE
Display icons

### ISSUE THREAD

**Issue by ihsansaleemkhan** [kkcodes/laravel-firebase-auth#4]
when I am run http://localhost:8000/auth/login path i am getting blank just i got 'login' heading only
![capture](https://user-images.githubusercontent.com/33631614/41989816-33d32b06-7a5e-11e8-8dc1-67cd91afb537.PNG)

**Comment by kkcodes** [comment]
Hi,

Have you followed these steps:

php artisan vendor:publish --provider="Kkcodes\FirebaseAuth\FirebaseAuthServiceProvider"

php artisan migrate

composer dump-autoload

php artisan db:seed --class=FirebaseSigninSourceTableSeeder

If you haven't then do follow these steps and also add the .env KEY VALUE pairs.
If you have, do check that in the database there are tables named as firebase_users, firebase_signin_source.

If not, then do follow these steps:
php artisan vendor:publish

It will give you option to select among a list, Select the one saying Kkcodes.

Then again perform the following steps:

php artisan migrate

composer dump-autoload

php artisan db:seed --class=FirebaseSigninSourceTableSeeder

**Comment by ihsansaleemkhan** [comment]
Thanks for the reply, I did those steps i go through the option one

**Comment by kkcodes** [comment]
Is it working now?

**Comment by ihsansaleemkhan** [comment]
Not working

**Comment by akshay-kapase** [comment]
same error here

**Comment by kkcodes** [comment]
The plugins is not installed correctly from your end, Do check that the vendor files are published, only then the package will work.
